version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-strapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: strapi-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "${PORT}:1338"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data: